### ISSUE TITLE
[BUGFIX] Appbar alignment is bugging when clicking on user image when logged in, also add a button with wallet icon to direct users to the wallet page 

### ISSUE THREAD

**Issue by cb7chaitanya** [code100x/tiplink#111]
[screen-capture.webm](https://github.com/user-attachments/assets/f442f334-06a8-48db-84a3-b0f300ebc36d)

-Take an updated pull of the dev-frontend branch and commit your changes there after fix

**Comment by cb7chaitanya** [comment]
Also add the select wallet button here when logged in

**Comment by Ameerjafar** [comment]
working on it @cb7chaitanya

**Comment by Ameerjafar** [comment]
@cb7chaitanya I have resolved the issue in this pr #114
