### ISSUE TITLE
[FIX] We don't need a signup with google button when user is logged in 

### ISSUE THREAD

**Issue by cb7chaitanya** [code100x/tiplink#112]
![Screenshot (80)](https://github.com/user-attachments/assets/9ad8a414-d270-4126-8c3c-ab132ab7e312)

-Take an updated pull of dev-frontend branch and commit your changes there

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
I am solving it @cb7chaitanya

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
Done @cb7chaitanya check it #113  fixes it

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
@cb7chaitanya look into  PR #113 ..
