### ISSUE TITLE
Add Multiple Wallet Adapters, Custom RPC

### ISSUE THREAD

**Issue by Manice18** [code100x/tiplink#118]
## Describe the bug
Currently, there are only 3 wallets present to connect, and there is no support for a custom RPC URL which is needed since the Solana devnet has issues like timeouts 
## Branching
- dev-frontend
## To Reproduce
 Click on the wallet button
## Expected Behaviour
There should be support for multiple wallet adapters, and custom RPC
## Screenshots
<img width="906" alt="image" src="https://github.com/user-attachments/assets/1572c3f5-c6e0-43e9-bb69-c73d55930ad1">

## Additional context
Fixing this issue adds multiple wallet adapters and support for custom RPC endpoints for eg: Helius

**Comment by cb7chaitanya** [comment]
Closing this as completed
