### ISSUE TITLE
create the wallet page in the user profile.

### ISSUE THREAD

**Issue by Ameerjafar** [code100x/tiplink#12]
currently we don't have user wallet page(frontend).

**Comment by Ameerjafar** [comment]
@cb7chaitanya can i work on that.

**Comment by ameeetgaikwad** [comment]
I can help as well!

**Comment by cb7chaitanya** [comment]
Pushing a template page for you guys to start working on

**Comment by ameeetgaikwad** [comment]
> Pushing a template page for you guys to start working on
> 

Thank you man! Can you assign me

**Comment by Ameerjafar** [comment]
@cb7chaitanya I have almost created the template.

**Comment by Ameerjafar** [comment]
![Screenshot 2024-08-04 182918](https://github.com/user-attachments/assets/815d9aec-8af7-4a3d-a0f9-f12c003d7467)
I just have to add some of the buttons and footer the template is almost ready. @cb7chaitanya

**Comment by Ameerjafar** [comment]
@ameeetgaikwad would you like to work on withdraw and swap frontend

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
@Ameerjafar i would love to join

**Comment by ameeetgaikwad** [comment]
@Ameerjafar Yes I would!

**Comment by Ameerjafar** [comment]
I don't have figma file i just using tailwind css @ameeetgaikwad

**Comment by ameeetgaikwad** [comment]
@Ameerjafar alright! Will design it accordingly.

can you just elaborate more on it? Where should i create the component? On which page?

I've something like this on my mind. I would change the colors according to the tipilink color scheme.

![image](https://github.com/user-attachments/assets/273e1e18-a1de-4637-a31b-c7bbee1368f0)

**Comment by ameeetgaikwad** [comment]
> @Ameerjafar alright! Will design it accordingly.
> 
> can you just elaborate more on it? Where should i create the component? On which page?
> 
> I've something like this on my mind. I would change the colors according to the tipilink color scheme.
> 
> ![image](https://private-user-images.githubusercontent.com/76063569/355668428-273e1e18-a1de-4637-a31b-c7bbee1368f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMzA4MjIsIm5iZiI6MTcyMzEzMDUyMiwicGF0aCI6Ii83NjA2MzU2OS8zNTU2Njg0MjgtMjczZTFlMTgtYTFkZS00NjM3LWEzMWItYzdiYmVlMTM2OGYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDE1MjIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1NDk3MTY5ODk1ODhiNzNiNmIyMjc0Y2Y1ZDlmOGY3NWFkNzY1MTk1YThhZThhMzg4YjU5ZmZmNGM4NmMxYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EcPAA1Qznu825qN1Tf_VE4oIc5tWpSYessfEjT9e0ds)

@cb7chaitanya where should i add this component? In which page?

**Comment by cb7chaitanya** [comment]
Refer to this #32 @ameeetgaikwad

**Comment by Ameerjafar** [comment]
@ameeetgaikwad can you make the wallet page responsive if I push the wallet page code.

**Comment by ameeetgaikwad** [comment]
@Ameerjafar he man sure! Let me know when done!
