### ISSUE TITLE
Add pda generation on backend

### ISSUE THREAD

**Issue by Saty248** [code100x/tiplink#120]
are we using nextjs for the restapis or should we use express or nestjs as our backend? @cb7chaitanya

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
kindly look into the readme @Saty248

**Comment by cb7chaitanya** [comment]
We aren't going down the PDA's route, take a look at the notion doc in the readme

**Comment by Saty248** [comment]
found the idea from this notion link under the feature set https://axatbhardwaj.notion.site/Tiplink-47ebac1bab1b484d89fc5476c9860202 @cb7chaitanya

**Comment by axatbhardwaj** [comment]
> found the idea from this notion link under the feature set https://axatbhardwaj.notion.site/Tiplink-47ebac1bab1b484d89fc5476c9860202 @cb7chaitanya

hi @Saty248 

we are currently exploring stuff over notion you are more than welcome to contribute to the research and the PDA creation part is going to be done at phase 2 of v1 

we are going to create issues for the same on github when we seek contributions 

please connect with @cb7chaitanya over discord if you want to discuss stuff

**Comment by Saty248** [comment]
thanks @axatbhardwaj .. @cb7chaitanya whats your discord id plz? also ig we can close this issue for now.

**Comment by cb7chaitanya** [comment]
@Saty248 0xchaitanya, you can ping me on cohort's discord

**Comment by Saty248** [comment]
We spoke few days back, my discord id is zeher
