### ISSUE TITLE
feature: Improve CI/CD workflows

### ISSUE THREAD

**Issue by pawann-2000** [code100x/tiplink#123]
**Is your feature request related to a problem? Please describe.**
Currently, the CI CD workflows are trivial.

**Describe the solution you'd like**
It would be great to include various additional workflows, for example pointing out library vulnerabilities, auto approval of linting, code quality checks and additional convenience for maintainers.

I am willing to raise a PR and already have the code locally ready for the workflow revamp.

**Comment by axatbhardwaj** [comment]
> **Is your feature request related to a problem? Please describe.** Currently, the CI CD workflows are trivial.
> 
> **Describe the solution you'd like** It would be great to include various additional workflows, for example pointing out library vulnerabilities, auto approval of linting, code quality checks and additional convenience for maintainers.
> 
> I am willing to raise a PR and already have the code locally ready for the workflow revamp.

would love to know the specifics 

as it is in early stages , what we can do to improve the CI/CD flow will appreciate more clarity

**Comment by pawann-2000** [comment]
Sure, here is the plan of action I have,

1. Implementing code scanning for security vulnerabilities.
2. Secret scanning to avoid accidental secret key pushes. (can be ruled out but nice to have)
3. Implement dependabot to upgrade dependencies from time to time, this offloads some weight from developers to manually upgrade the deps.
4. Approve pull requests on a reaction or text (can be also ruled out but is helpful from a maintainer's perspective).

**Comment by ghost** [comment]
@pawann-2000 but suppose somebody pushes secret key and the cicd fails and we close the pr but anyone can see the closed pr from pr history
Its good to improve cicd but i think we should also introduce a script which will scan the code to avoid security vurnerability
And give us a warning before pushing the code

**Comment by pawann-2000** [comment]
> @pawann-2000 but suppose somebody pushes secret key and the cicd fails and we close the pr but anyone can see the closed pr from pr history Its good to improve pr but i think we should also introduce a script which will scan the code to avoid security vurnerability And give us a warning before pushing the code

Yes, that's what I have as plan 2

**Comment by axatbhardwaj** [comment]
> > @pawann-2000 but suppose somebody pushes secret key and the cicd fails and we close the pr but anyone can see the closed pr from pr history Its good to improve pr but i think we should also introduce a script which will scan the code to avoid security vurnerability And give us a warning before pushing the code
> 
> Yes, that's what I have as plan 2

@pawann-2000 start implementing all these mentioned features you are good to go 

@cb7chaitanya would love to have your insights on this

**Comment by cb7chaitanya** [comment]
@pawann-2000 Please start with this and make a PR, we can go from there

**Comment by pawann-2000** [comment]
Roger, will keep you guys posted

**Comment by cb7chaitanya** [comment]
@pawann-2000 any update on this?

**Comment by vishutyagi0210** [comment]
**for Code-scanning. only**
we can user Semgrep because it is an efficient and open-source tool that fits well into our project for several reasons.
Fast & Lightweight

Customizable : for example ~  if you want to prevent developers from using console.log in production code, or ensure that certain security checks are always included, you can write a custom rule in a .semgrep.yml file.

Language Support
Free & Open-source

Easy Integration via github actions

**Comment by cb7chaitanya** [comment]
Cool, you can get on it @vishutyagi0210

**Comment by Gmin2** [comment]
Hey @cb7chaitanya , can we use sonarcloud here, and can i work on it

**Comment by cb7chaitanya** [comment]
Haven't used it before, do send some docs on it @Gmin2

**Comment by vishutyagi0210** [comment]
@Gmin2 , I agree that we can leverage SonarCloud, as it's highly effective for custom code quality analysis. It offers:

~ In-depth static analysis of our TypeScript/JavaScript code
~ Identification of code smells, potential bugs, and maintainability issues in custom code
` Tracking of code quality metrics over time

@cb7chaitanya , we should continue using Trivy for dependency and Docker security, as that’s not the primary focus of SonarCloud. By keeping both tools, we’ll ensure comprehensive coverage for both code quality and security.

Feel free to ping me if you’d like more details on either tool!
