### ISSUE TITLE
Hero Image is too big

### ISSUE THREAD

**Issue by vatan45** [code100x/tiplink#124]
<img width="1465" alt="Screenshot 2024-08-21 at 1 28 06 PM" src="https://github.com/user-attachments/assets/583fa0e6-22b1-45d3-b0de-ee07a3d0edb9">
hero image is too big and have to scroll to view complete image, that's bit annoing, will look more profession if make it visible in one scroll

**Comment by sahajkedia** [comment]
I would like to take this up and fix it.

**Comment by vatan45** [comment]
> I would like to take this up and fix it.

Already fixed sir raised a pr
