### ISSUE TITLE
fix the Profile Bar in '/wallet' page

### ISSUE THREAD

**Issue by rhithesh** [code100x/tiplink#129]
<img width="1440" alt="Screenshot 2024-08-28 at 2 22 20 AM" src="https://github.com/user-attachments/assets/73bc7917-1d8e-44be-b5de-c54e780df9b4">
use useSession() hook from next auth and make it similar to the / page

I would like to work on this issue

**Comment by Satyajit-Sahoo45** [comment]
can I work on this issue?

**Comment by ghost** [comment]
@Satyajit-Sahoo45
@rhithesh  
#132 already fixes it,I have raised a  pr

**Comment by ghost** [comment]
kindly pull the latest changes

**Comment by cb7chaitanya** [comment]
Closing this as completed
