### ISSUE TITLE
[FEAT]: Implemented Logout functionality.

### ISSUE THREAD

**Issue by BearerOP** [code100x/tiplink#130]
### **📜 Description**

Currently, at '/wallet' route Logout button is not working.

### **👟 Reproduction steps**

Go to the Wallet Page.
Click on the Logout button.
Notice that it is not logging the user out.
Users currently have to go to the root route for logging out.

https://github.com/user-attachments/assets/a9c0927e-fbcf-48f3-8bca-f12373abeade

### **👍 Expected behavior**
When the "Logout" button is clicked it needs to log out the user and redirect to the home page or landing page i.e. '/' .

https://github.com/user-attachments/assets/390b253d-e661-4198-8a49-a5f3d8f99558

### **👀 Have you spent some time to check if this bug has been raised before?**

 ✅ I checked and didn't find similar issue

### **🏢 Have you read the Contributing Guidelines?**

✅ I have read the [Contributing Guidelines](https://github.com/code100x/tiplink/blob/dev/contributing.md)

**Comment by Satyajit-Sahoo45** [comment]
is this issue still open? I would like to work on it.

**Comment by BearerOP** [comment]
> is this issue still open? I would like to work on it.

I had already pulled request for it and it is still about to be reviewed.

**Comment by ghost** [comment]
@BearerOP logout works already

**Comment by BearerOP** [comment]
> @BearerOP logout works already

seems it's not working only for me?

**Comment by ghost** [comment]
its working check pr #132  its merged

**Comment by ghost** [comment]
and home page logout also works

**Comment by BearerOP** [comment]
do later PRs get reviewed before earlier ones?

> its working check pr #132 its merged

**Comment by ghost** [comment]
@BearerOP sir i have done the logout funtionality of the wallet page and you are doing the home page.It was working fine.Maybe you dont have the latest pull.Which you are solving is already solved 2 months ago.Kindly check it thanks

**Comment by BearerOP** [comment]
Okay got it, no worries.
