### ISSUE TITLE
[Feat] Implementation of Encryption of shares 

### ISSUE THREAD

**Issue by axatbhardwaj** [code100x/tiplink#136]
**Todo:-**

1. encrypt shares using best encryption algo/method to encrypt 

before starting with implementation would love to have a small research note (notion doc preferably) on how you've chosen a specific Algo/method for encryption and why

after the discussion would assign the issue then you can start implementing

it is not to scrutinize anyone just to make rational decision

**Comment by Sahid-m** [comment]
Do you mean encryption of private key shards or what is share in this context? Would like to work on this but need some clarity before researching for encryption algorithm

**Comment by axatbhardwaj** [comment]
> Do you mean encryption of private key shards or what is share in this context? Would like to work on this but need some clarity before researching for encryption algorithm

yes 

i meant the shares of private key only and i think it(documentation) is available on the notion doc present in project readme 

Please let me know it isn't

Cheers !!

**Comment by lakshayvaishnav** [comment]
hey  @axatbhardwaj ,  I've created a Notion document that outlines various encryption methods suitable for encrypting the shards in our project. 

[notion doc](https://marbled-egg-d6d.notion.site/Encryption-algos-6c638723f0e2460c9ee28e2c92d948ec)

Please take a look when you have a chance and let me know if you have any feedback!

**Comment by axatbhardwaj** [comment]
> hey @axatbhardwaj , I've created a Notion document that outlines various encryption methods suitable for encrypting the shards in our project.
> 
> [notion doc](https://marbled-egg-d6d.notion.site/Encryption-algos-6c638723f0e2460c9ee28e2c92d948ec)
> 
> Please take a look when you have a chance and let me know if you have any feedback!

Hi @lakshayvaishnav 

Thank you for the doc and i would love to know in a few lines why should we use AES256 for symmetric encryption and not any other algo

**Comment by lakshayvaishnav** [comment]
> > hey @axatbhardwaj , I've created a Notion document that outlines various encryption methods suitable for encrypting the shards in our project.
> > [notion doc](https://marbled-egg-d6d.notion.site/Encryption-algos-6c638723f0e2460c9ee28e2c92d948ec)
> > Please take a look when you have a chance and let me know if you have any feedback!
> 
> Hi @lakshayvaishnav
> 
> Thank you for the doc and i would love to know in a few lines why should we use AES256 for symmetric encryption and not any other algo

well , first of all it is really tough to crack because of its strong encryption , it is faster and efficient as compared to other algos so it wont slow down our dapp and lastly it is widely accepted and trusted by many other blockchain platforms and web3 projects.

**Comment by axatbhardwaj** [comment]
> > > hey @axatbhardwaj , I've created a Notion document that outlines various encryption methods suitable for encrypting the shards in our project.
> > > [notion doc](https://marbled-egg-d6d.notion.site/Encryption-algos-6c638723f0e2460c9ee28e2c92d948ec)
> > > Please take a look when you have a chance and let me know if you have any feedback!
> > 
> > Hi @lakshayvaishnav
> > 
> > Thank you for the doc and i would love to know in a few lines why should we use AES256 for symmetric encryption and not any other algo
> 
> well , first of all it is really tough to crack because of its strong encryption , it is faster and efficient as compared to other algos so it wont slow down our dapp and lastly it is widely accepted and trusted by many other blockchain platforms and web3 projects.
> 

clone and look at the encryption branch from the repo

 let's connect over discord if you have some doubts
