### ISSUE TITLE
[CHORE] Code cleanup to make the wallet page components cleaner

### ISSUE THREAD

**Issue by cb7chaitanya** [code100x/tiplink#137]
- The current UI components on Wallet page have too many elements we currently don't support or don't plan to
- The current UI components on Wallet page work but code quality can be highly improved
- Tag this as CHORE 
- Make a PR to dev frontend and take an updated pull too before attempting the issue

**Comment by BearerOP** [comment]
I am willing to work on it, could you please tell the components to be kept and removed among these: "Buy", "Crowd Fund", "NFTs", "Assets", "Pro Version", "Blogs".

Appbar on the home page is not responsive, should I create different issue for it or continue in this issue only.

**Comment by cb7chaitanya** [comment]
Exactly the thing is, we don't need Crowd funding, Pro version or blogs 

Assets, NFTs', Buy is enough, we don't need to add Blogs/Pro version and all, the actual amount of things needed or supported are less than what is listed, most of which can be accomodated in one sidebar, so you can start with that

**Comment by BearerOP** [comment]
> Exactly the thing is, we don't need Crowd funding, Pro version or blogs
> 
> Assets, NFTs', Buy is enough, we don't need to add Blogs/Pro version and all, the actual amount of things needed or supported are less than what is listed, most of which can be accomodated in one sidebar, so you can start with that

Okay then I am working on it.

**Comment by cb7chaitanya** [comment]
Closing this as completed
