### ISSUE TITLE
[FEAT] Improvement of Wallet UI page

### ISSUE THREAD

**Issue by cb7chaitanya** [code100x/tiplink#144]
- Take an update pull and compare our wallet component UI with this 
https://github.com/code100x/tiplink/issues/23
- Also add a bit more spacing between buttons in the left sidebar component in the wallet page 
- Add margins on either side of the topbar to make it a bit more compact 
- If you have any other UI suggestions, please give a screenshot in comments, and work on them after being accepted

**Comment by that-avg-dev** [comment]
would like to take up this issue , @cb7chaitanya ,  please assign it to me .

**Comment by cb7chaitanya** [comment]
Cool, you can work on it @kairveeehh

**Comment by Ameerjafar** [comment]
@cb7chaitanya can you assign me this issue to work on.

**Comment by cb7chaitanya** [comment]
Feel free to pick it up

**Comment by that-avg-dev** [comment]
> Feel free to pick it up

@cb7chaitanya can you provide the authentication details so that I am able to work on it ?

**Comment by Bhushan-04** [comment]
![Screenshot (289)](https://github.com/user-attachments/assets/147dddcb-67a7-44d8-8707-bf6167a276c6)
![Screenshot (288)](https://github.com/user-attachments/assets/6dde9f6f-dc3f-4b54-b5be-08e6b1407431)

let me know if any other changes to make here

**Comment by cb7chaitanya** [comment]
@Bhushan-04 I don't like these changes, can you make the changes out to be what I suggested initially in the issue

**Comment by cb7chaitanya** [comment]
@kairveeehh We haven't deployed the app, neither a deployed database nor the app, so can't give you a dummy user for now, do it the normal way for now by setting up google oAuth credentials, would create a dummy user when we have productionised the web app

**Comment by that-avg-dev** [comment]
> @kairveeehh We haven't deployed the app, neither a deployed database nor the app, so can't give you a dummy user for now, do it the normal way for now by setting up google oAuth credentials, would create a dummy user when we have productionised the web app 

Ok it actually gives error if I try to do it , but I will try again using sm dummy user

**Comment by Bhushan-04** [comment]
> @Bhushan-04 I don't like these changes, can you make the changes out to be what I suggested initially in the issue
Sure

**Comment by Bhushan-04** [comment]
@cb7chaitanya sure

**Comment by dhruv-colosus** [comment]
@cb7chaitanya Should I take this up

**Comment by cb7chaitanya** [comment]
@kairveeehh What is the error that you get, send the issue, let's debug it
