### ISSUE TITLE
Update CONTRIBUTING.md to be Clearer, More Concise, and Beginner-Friendly

### ISSUE THREAD

**Issue by NegiSushant** [code100x/tiplink#15]
Our current **CONTRIBUTING.md** file contains valuable information, but it could benefit from being more clear, concise, and beginner-friendly. This would help encourage more contributions from new developers and ensure that everyone understands the contribution process.

A more organized, clear, and beginner-friendly CONTRIBUTING.md file that lowers the barrier to entry for new contributors and provides all necessary information in a concise manner.

**Comment by cb7chaitanya** [comment]
Suggest some changes @NegiSushant
