### ISSUE TITLE
[FEAT] Coupling of keypair generation with encryption and key splitting module

### ISSUE THREAD

**Issue by cb7chaitanya** [code100x/tiplink#165]
Tasks to do 
- Save the public key directly into the database after keypair generation on signing up
- After splitting the private key into 3 shares, encrypt the first share using the AES module in the latest commit and save that share in the database

**Comment by rahulbarmann** [comment]
I would like to work on this @cb7chaitanya

**Comment by cb7chaitanya** [comment]
Sure, go ahead @rahulbarmann
