### ISSUE TITLE
[FIX] Appbar orientation fix 

### ISSUE THREAD

**Issue by cb7chaitanya** [code100x/tiplink#167]
[screen-capture (1).webm](https://github.com/user-attachments/assets/c8d42226-b78f-4ac0-bd71-ee5dd4ba0555)

- Take an updated pull and just check the appbar issue out on the landing page
- Fix this orientation issue for the same

**Comment by anuragnegi000** [comment]
can i try

**Comment by cb7chaitanya** [comment]
Sure, go ahead @anuragnegi000

**Comment by cb7chaitanya** [comment]
Just an idea that came to mind, you can try and replicate Job Board's navbar but with our own UI theme being consistent @anuragnegi000

**Comment by anuragnegi000** [comment]
> Just an idea that came to mind, you can try and replicate Job Board's navbar but with our own UI theme being consistent @anuragnegi000

sure

**Comment by cb7chaitanya** [comment]
Closing this as completed
