### ISSUE TITLE
[FEAT] Coupling splitting service with AWS and GCP KMS modules 

### ISSUE THREAD

**Issue by cb7chaitanya** [code100x/tiplink#168]
- Take an updated pull to get the modified schema file 
- Utilize the already existing Splitting service to split the private key and KMS modules to encrypt share number 2 & number 3 
- Store those shares in the respective database fields in the user table 
- This goes without saying but to do this, you need to configure KMS, you can refer to the docs I have listed out in the Readme

Do tell if you want to do both KMS or just one

**Comment by rahulbeeram12** [comment]
Hey, can i work on this issue?

**Comment by cb7chaitanya** [comment]
Assigned
