### ISSUE TITLE
[FEAT] Create a server action for decrypting shares and piecing all the shares together 

### ISSUE THREAD

**Issue by cb7chaitanya** [code100x/tiplink#169]
- Utilize pre existing decryption modules for decrypting private key share 1, 2 and 3 
- Piece the decrypted shares together in the order of: aesShare, awsShare and gcpShare respectively 
- Return the share that got pieced together as one 

Please take an updated pull

This will be a wrapper function which is called whenever a transaction has to be signed, to get a decrypted private key

**Comment by rahulbarmann** [comment]
Can I work on this issue?

**Comment by cb7chaitanya** [comment]
Yep yep pick it up @rahulbarmann
