### ISSUE TITLE
Add sidemenu or other UI elements/feature

### ISSUE THREAD

**Issue by KushalBhanot** [code100x/tiplink#17]
Let me know @cb7chaitanya if I can pick anything up.

**Comment by jyotishman-pathak** [comment]
Can you assign me the task of integrating the UI for this project?

**Comment by Satyajit-Sahoo45** [comment]
can I work on this?

**Comment by Praashh** [comment]
> Let me know @cb7chaitanya if I can pick anything up.

not much needed for now guys, you guys can work on wallet landing pages

**Comment by jyotishman-pathak** [comment]
hey sounds cool I can do it assign it to me

**Comment by KushalBhanot** [comment]
> > Let me know @cb7chaitanya if I can pick anything up.
> 
> 
> 
> not much needed for now guys, you guys can work on wallet landing pages

Can you make issues and assign them?

**Comment by Praashh** [comment]
> cb7chaitanya

cb7chaitanya will do it.

**Comment by Aarif5435** [comment]
is there any feature or issue I can work on that ? @KushalBhanot  @Praashh

**Comment by Praashh** [comment]
will be opening soon.

**Comment by Aarif5435** [comment]
> will be opening soon.

okay please assign that one to me.

**Comment by OmkarK97** [comment]
Is this issue still open..

**Comment by OmkarK97** [comment]
I would like to contribute to this

**Comment by Ameerjafar** [comment]
@Praashh  can i work on this.
