### ISSUE TITLE
[BUG] Appbar rendering issue

### ISSUE THREAD

**Issue by cb7chaitanya** [code100x/tiplink#172]
[screen-capture (2).webm](https://github.com/user-attachments/assets/fdd7958a-b6db-47ff-aaef-b28d5c4c8ee8)

Session is picked up after the page fully loads and therefore leading to a delay in the rendering of user image and wallet icon 

- Take an updated pull and make changes to dev

**Comment by Ameerjafar** [comment]
@cb7chaitanya assign me brother

**Comment by cb7chaitanya** [comment]
Assigned @Ameerjafar

**Comment by Ameerjafar** [comment]
@cb7chaitanya for this can i add the loading till the session picked up.

**Comment by cb7chaitanya** [comment]
@Ameerjafar  You have to take a new fork to work on this, please keep your work seperate, take a new fork as commit history has been rewritten

**Comment by Ameerjafar** [comment]
Ok sir @cb7chaitanya

**Comment by Ameerjafar** [comment]
@cb7chaitanya simple loading is fine in the image part and the wallet part?
