### ISSUE TITLE
[BUG] Orientation Fix for wallet-adapter page

### ISSUE THREAD

**Issue by cb7chaitanya** [code100x/tiplink#173]
[screen-capture (3).webm](https://github.com/user-attachments/assets/bf712628-c6e7-45a3-a6b9-db1237efb894)

- The wallet-adpater page's orientation is bonked, fix it
- Do take a pull of dev to get the latest code changes

**Comment by Ameerjafar** [comment]
@cb7chaitanya  assign me brother

**Comment by cb7chaitanya** [comment]
Assigned, go for it @Ameerjafar
