### ISSUE TITLE
Only Google used as Provider for nextauth

### ISSUE THREAD

**Issue by pruthviraj7714** [code100x/tiplink#18]
can't we use more providers & a form with username, email & password.

**Comment by cb7chaitanya** [comment]
See original tiplink, for now we are just using google auth

**Comment by pruthviraj7714** [comment]
@cb7chaitanya can I add things like github provider & also signin & signup page

**Comment by Praashh** [comment]
> can't we use more providers & a form with username, email & password.

we can't actually, tiplink is basically a web-based wallet, where a user can setup it using google OAuth.

**Comment by pruthviraj7714** [comment]
@Praashh Okay
