### ISSUE TITLE
Login Button Remains Visible After Google OAuth2.0 Login

### ISSUE THREAD

**Issue by kushwahramkumar2003** [code100x/tiplink#19]
# Issue: Login Button Remains Visible After Google OAuth2.0 Login

## Description

When using Google OAuth2.0 for authentication with NextAuth, the login button continues to display even after a successful login. Instead of showing the user's profile picture and other details, the UI remains unchanged with the login button still visible.

## Steps to Reproduce

1. Navigate to the login page of the application.
2. Click on the "Login with Google" button.
3. Complete the Google OAuth2.0 authentication process.
4. Observe that the login button is still visible on the page.

## Expected Behavior

After a successful login with Google OAuth2.0, the application should:
- Hide the login button.
- Display the user's profile picture, email, and any other relevant details in place of the login button.

## Actual Behavior

- The login button remains visible even after a successful login.
- The user's profile picture and details are not displayed.

### Before Login

![tiptool-issue-1](https://github.com/user-attachments/assets/cef660f5-f54e-4f3f-8c64-e58e9f0d14cf)
### After Login

![tiptool-issue-1](https://github.com/user-attachments/assets/6ce16b59-0731-4cf1-b944-2e9cbce1fed1)

**Comment by cb7chaitanya** [comment]
That is because session is not setting, i am on it
