### ISSUE TITLE
[QUESTION] IS THERE ANY DESIGN FOR WALLET ADAPTER PAGE 

### ISSUE THREAD

**Issue by ankitmrmishra** [code100x/tiplink#191]
#### Is it the correct approach to open the wallet page only after the user logs in, or redirect the user to the wallet adapter page  after connecting a wallet only without the user logging in? 
![image](https://github.com/user-attachments/assets/53a68c1e-6c78-4d80-82da-3ef21a2ab1f1)

**Comment by cb7chaitanya** [comment]
Please take an updated pull, possibly a new fork, take a look at the updated readme file for more info
Also I took a look at your fork, it only has a copy of the main branch, we are working off of the dev branch 
This page has completely changed, and is undergoing redesign along with the others, hence the issue #183

**Comment by ankitmrmishra** [comment]
Ok thanks @cb7chaitanya, closing this issue.
