### ISSUE TITLE
[FEAT] Create a nested User interface for send functionality

### ISSUE THREAD

**Issue by cb7chaitanya** [code100x/tiplink#201]
- Have 2 options for sending SOL through tiplink
- One being Send Via New tiplink
- One being Send to a new wallet address
- Goes without mentioning that this has to be done within the wallet interface

- Take inspiration from [tiplink.io](https://tiplink.io/) for the send interface

**Comment by wraith2009** [comment]
assign this to me will need some advice tho

**Comment by anshuman008** [comment]
hey i would like to take this issue! can you please assign it to me @cb7chaitanya !
