### ISSUE TITLE
[FEAT] Create an interface to support recieving SOL in the tiplink wallet

### ISSUE THREAD

**Issue by cb7chaitanya** [code100x/tiplink#202]
- We are supporting 2 options to get public key when clicking on recieve button within the wallet interface
- First option should be getting public key of the user via QR code
- Second option would be getting the public key in plain text to copy

For reference, check out Phantom's Interface

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
Assign me

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
@cb7chaitanya #211 Solves it Kindly Review it
