### ISSUE TITLE
[FEAT] Create an interface for swapping tokens on Solana via tiplink 

### ISSUE THREAD

**Issue by cb7chaitanya** [code100x/tiplink#204]
- This is to be powered by Jupiter, so do research about it to leverage it here 
- You don't have to add the Swapping functionality powered by Jupiter as of now, but can take this up after this issue has been resolved

Take reference of https://tiplink.io/ for the same

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
I  am taking the ui interface then for now then will look into the jupiter price fetching and insufficient balance later 
can i take this sir ? @cb7chaitanya

**Comment by anshuman008** [comment]
can i join you @Rudra-Sankha-Sinhamahapatra @cb7chaitanya !

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
Sure @anshuman008

**Comment by cb7chaitanya** [comment]
Assigned @Rudra-Sankha-Sinhamahapatra @anshuman008

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
Done #214 Check @cb7chaitanya
