### ISSUE TITLE
Improve the UI to our own better version, different from the TipLinks UI.

### ISSUE THREAD

**Issue by Pawank06** [code100x/tiplink#23]
**This PR aims to enhance our user interface by differentiating it from the TipLinks UI and creating a better version. The changes include:**

- Redesigning the layout for a more user-friendly and mono-chromatic look.
- Updating color schemes.
- Adding new visual elements for improved aesthetics
- Optimizing the interface for better performance and responsiveness

**Changes:**

1. **Layout Improvements:**
    - Redesigned the main layout to be more intuitive and visually appealing.
    - Removed elements that were directly copied from TipLinks.
2. **Color Schemes:**
    - Introduced a new color palette that aligns with our brand identity.
3. **Visual Enhancements:**
    - Added new icons and images to enhance the visual appeal.
    - Improved spacing and alignment for a cleaner appearance.
4. **Performance Optimization:**
    - Refactored CSS and JavaScript for better performance.
    - Ensured that the UI is responsive across different devices and screen sizes.

**Screenshots:**

**Before:**

![image](https://github.com/user-attachments/assets/37f0b7c4-c23d-4e04-a260-60a5a069d3bf)

**After:**

![image](https://github.com/user-attachments/assets/f570674e-426a-4a8b-a26c-945c2f641773)

**Before:**

![image](https://github.com/user-attachments/assets/d0cca992-2612-4804-92e4-231388661347)

**After:**

![image](https://github.com/user-attachments/assets/0e4ab2a0-b2bb-4fc8-9a61-a77262034272)

**Before:**

![image](https://github.com/user-attachments/assets/a75d5191-9fe0-432a-ac7e-bfa99b6f2633)

**After:**

![image](https://github.com/user-attachments/assets/2708980d-d29b-402a-acde-931d103a0301)

**Testing:**

- [x]  Verified that the new UI works well on different browsers (Chrome, Firefox, Safari)
- [x]  Tested responsiveness on mobile and tablet devices
- [x]  Confirmed that all existing functionality remains intact

**Additional Notes:**

- Please review the new design and provide feedback. If you are okay with it, I will start making changes according to feedback and complete the UI.

@cb7chaitanya

**Comment by cb7chaitanya** [comment]
Ngl, i love this theme, you can get on with it, starting with the landing page

**Comment by Pawank06** [comment]
> Ngl, i love this theme, you can get on with it, starting with the landing page

I was waiting for your reply. I will make the PR soon.

**Comment by Ameerjafar** [comment]
@Pawank06 have you used figma or you have wriitten your entire code in tailwind css?

**Comment by Pawank06** [comment]
> @Pawank06 have you used figma or you have wriitten your entire code in tailwind css?

I used Figma to design the website and Tailwind CSS to implement the design.

**Comment by Ameerjafar** [comment]
@Pawank06 can you share the figma file for wallet page responsive as well.
