### ISSUE TITLE
Docker file doesn't seems right and I think we also need to first create a migration file.

### ISSUE THREAD

**Issue by ArpitBlagan** [code100x/tiplink#4]

**Comment by cb7chaitanya** [comment]
What exactly, please point it out and you can work on this after that @ArpitBlagan

**Comment by ArpitBlagan** [comment]
> What exactly, please point it out and you can work on this after that @ArpitBlagan

1. As in current docker file there is a line RUN npm run dev  I think we dont' need this and we need to put this in cmd CMD ["npm","run","dev"] because this is an command which will be keep listening to in coming requests for our app.

2. As there is no migration file in prisma we need to create on before starting the app and also need to add health check for db in our docker compose.
