### ISSUE TITLE
Feat - Add light/dark mode

### ISSUE THREAD

**Issue by vanshavenger** [code100x/tiplink#49]
Should i go ahead and raise PR for light and dark mode with View transition API?

**Comment by vanshavenger** [comment]
Can add prettier, husky, light dark mode with a PR, i ahve already made them in local, @cb7chaitanya  should i push them

**Comment by anuragnegi000** [comment]
We can use ShadCN for using light and dark mode, assign me this i would like to work into this

**Comment by cb7chaitanya** [comment]
Not needed, refer #3

**Comment by vanshavenger** [comment]
Okay
