### ISSUE TITLE
Create documentation for the repository

### ISSUE THREAD

**Issue by cb7chaitanya** [code100x/tiplink#5]
-Add a contributing.md for contribution guidelines
-Add PR and issue templates with descriptions on how a PR/issue should look depending on the type of PR

And more documentation you can think of, just tell me about it before getting on with that work

**Comment by mehetab-01** [comment]
i want to work on this

**Comment by Saurabhchaddha6** [comment]
Interested, you can assign me!

**Comment by ankitkuxt** [comment]
i would like to work on this

**Comment by shashidharaa** [comment]
I would love to work on this. Please assign this to me

**Comment by Anshgrover23** [comment]
@cb7chaitanya hi bro made one pr related to it plss review

**Comment by jyotishman-pathak** [comment]
hey interested in working you can assign it to me

**Comment by PoulavBhowmick03** [comment]
I would like to work on it
1. A `contributing.md` for contributors to get started with and create issues, make PR, complete guide
2. A `PR Template` 
3. An `issue` template
Hoping to get assigned to this
@cb7chaitanya
