### ISSUE TITLE
Linting Warnings

### ISSUE THREAD

**Issue by Rudra-Sankha-Sinhamahapatra** [code100x/tiplink#53]
There are linting errors in this repository ...this needs to be fixed
#56  solves it
![image](https://github.com/user-attachments/assets/ea5c8cdd-bffc-4488-b084-8895e27aedaa)

**Comment by vanshavenger** [comment]
@Rudra-Sankha-Sinhamahapatra ig we should keep it Image and make it Unoptimized as of now instead of usng img

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
yeah but everyone is using img tag thats why i didnt use Image 
@cb7chaitanya  kindly look into this

**Comment by vanshavenger** [comment]
Agree but since we using next js ig should use its features.

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
everybody is using img tag as of now ,every new pr consists of img tag so keep it img as now ,we will use Image later
