### ISSUE TITLE
Workflow issue

### ISSUE THREAD

**Issue by Rudra-Sankha-Sinhamahapatra** [code100x/tiplink#59]
Currently only main branch pull requests are having workflow checks ,make it to all branches 
and add a build.yml for build workflow

![image](https://github.com/user-attachments/assets/187a2619-3b50-4665-98e3-97c683f51f5e)

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
#60 fixes it , hey @cb7chaitanya please sync all the branches with main so that they can have workflows and the linting issue fixes which i have fixed before
Thanks

**Comment by Praashh** [comment]
why for all branches? the standard approach is to have workflow checks in main or master branch.

can you please explain why we need workflow checks for all the branches?
