### ISSUE TITLE
Invalid src prop issue with external image hostname not configured in next.config.js

### ISSUE THREAD

**Issue by Riya267** [code100x/tiplink#70]
### Description: Encountering an issue with the next/image component in my Next.js project. The error message is:

![Screenshot 2024-08-08 at 7 21 25 PM](https://github.com/user-attachments/assets/f30aa530-302d-46c9-ae98-b330e18a8e13)

This error occurs when we try to use an image from the URL https://lh3.googleusercontent.com.

### Expected Behavior:
The image should be rendered without any errors if the hostname is correctly configured in the next.config.js file.

### Actual Behavior:
An error is thrown indicating that the hostname "lh3.googleusercontent.com" is not configured under images in next.config.js.

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
@Riya267 you can close this issue as your PR has been already merged

**Comment by Riya267** [comment]
yup closing
