### ISSUE TITLE
Comma is missing in package.json after line 15

### ISSUE THREAD

**Issue by Riya267** [code100x/tiplink#84]
issue:- Comma is missing in package.json after line 15

![Screenshot 2024-08-08 at 8 00 20 PM](https://github.com/user-attachments/assets/4ddb08ea-78c7-4bda-81fe-553515227596)

**Comment by cb7chaitanya** [comment]
Go ahead, please fix it @Riya267

**Comment by Riya267** [comment]
> Go ahead, please fix it @Riya267

fixed

**Comment by Riya267** [comment]
I am closing this issue as its fixed now @cb7chaitanya
