### ISSUE TITLE
Display user image and logout option on logging in

### ISSUE THREAD

**Issue by PoulavBhowmick03** [code100x/tiplink#9]
## Current situation
Currently after logging in, it still displays "Login with Google"
![image](https://github.com/user-attachments/assets/ec0896f0-8598-4817-9d35-f4164f2efa0b)

## What should happen
On logging in, something like this should be displayed
![image](https://github.com/user-attachments/assets/26c9dcc2-d14e-4801-8708-6898f1b9344e)

## Steps
- go to src/components/Appbar.tsx
- import an additional SignOut from next-auth
- use the useSession to have a status
- check if status is authenticated or not and display accordingly

### I would love to raise a PR working on this

**Comment by cb7chaitanya** [comment]
Work is happening on this in #1 already

**Comment by PoulavBhowmick03** [comment]
alright!
