### ISSUE TITLE
Implement the Wallet Adapter page

### ISSUE THREAD

**Issue by cb7chaitanya** [code100x/tiplink#99]
-Create the wallet adapter information page
-Add your changes to the dev-frontend branch

**Comment by isrark005** [comment]
I'll get on this one

**Comment by cb7chaitanya** [comment]
Cool, you can start, pushing a sample wallet adapter page you can work on that @isrark005

**Comment by NeelContractor** [comment]
is this what you asked for?
https://github.com/anza-xyz/wallet-standard/tree/master/packages/wallets/ghost/src

**Comment by isrark005** [comment]
@NeelContractor no, this is about the page UI

**Comment by basedD3v** [comment]
@cb7chaitanya does this issue refer to the page which shows wallet/user info after user connects his wallet

this page:
<img width="1920" alt="Screenshot 2024-08-23 at 12 52 21" src="https://github.com/user-attachments/assets/816fab63-c9dc-4e01-8938-c7e211d55ad9">

**Comment by cb7chaitanya** [comment]
No @basedD3v this one 
https://tiplink.io/products/tiplink-wallet-adapter
